// ─── Note ────────────────────────────────────────────────────────────────────

export type NoteType =
  | "text"
  | "link"
  | "voice"
  | "task"
  | "meeting"
  | "file"
  | "highlight";

export type NoteStatus = "active" | "archived" | "deleted";

export interface Note {
  id: string;
  userId: string;
  type: NoteType;
  status: NoteStatus;
  content: string;
  contentMarkdown: string | null;
  sourceUrl: string | null;
  sourceTitle: string | null;
  metadata: NoteMetadata;
  createdAt: Date;
  updatedAt: Date;
}

export interface NoteMetadata {
  // voice
  transcription?: string;
  audioDuration?: number;
  // link
  ogImage?: string;
  ogDescription?: string;
  readingTime?: number;
  // file
  fileName?: string;
  fileSize?: number;
  mimeType?: string;
  // meeting
  attendees?: string[];
  duration?: number;
  // ai derived
  summary?: string;
  keyPoints?: string[];
}

// ─── Entity ───────────────────────────────────────────────────────────────────

export type EntityType = "person" | "company" | "project" | "topic" | "place";

export interface Entity {
  id: string;
  userId: string;
  type: EntityType;
  name: string;
  description: string | null;
  metadata: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Task ─────────────────────────────────────────────────────────────────────

export type TaskStatus = "todo" | "in_progress" | "done" | "cancelled";
export type TaskPriority = "low" | "medium" | "high" | "urgent";

export interface Task {
  id: string;
  userId: string;
  sourceNoteId: string | null;
  title: string;
  context: string | null; // AI-generated "why this matters"
  status: TaskStatus;
  priority: TaskPriority;
  dueDate: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Tag ──────────────────────────────────────────────────────────────────────

export interface Tag {
  id: string;
  userId: string;
  name: string;
  color: string | null;
  autoGenerated: boolean;
  createdAt: Date;
}

// ─── Collection ───────────────────────────────────────────────────────────────

export interface Collection {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  emoji: string | null;
  createdAt: Date;
  updatedAt: Date;
}

// ─── User ─────────────────────────────────────────────────────────────────────

export interface UserProfile {
  id: string;
  email: string;
  displayName: string | null;
  avatarUrl: string | null;
  settings: UserSettings;
  createdAt: Date;
}

export interface UserSettings {
  proactivityLevel: "quiet" | "normal" | "active";
  digestEnabled: boolean;
  digestTime: string; // HH:MM
  timezone: string;
  theme: "light" | "dark" | "system";
}

// ─── Search ───────────────────────────────────────────────────────────────────

export interface SearchResult {
  note: Note;
  score: number;
  excerpt: string;
  matchedEntities: Entity[];
}

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  citations?: CitedNote[];
}

export interface CitedNote {
  noteId: string;
  title: string;
  excerpt: string;
  createdAt: Date;
}

// ─── Capture ──────────────────────────────────────────────────────────────────

export interface CaptureInput {
  type: NoteType;
  content?: string;
  url?: string;
  audioBlob?: Blob;
  file?: File;
}
